@BASE_URL = http://localhost:/3000/api/buildings
@AUTH_TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwOWYzYTQ3LWQ3OWUtNDU3My05MjczLTlkMjMzNzc2MDUwMSIsImVtYWlsIjoibnVtYmVyLmRvZUBhcHAuY29tIiwicm9sZSI6Ik1hbmFnZXIgcm9sZSIsImlhdCI6MTc3MTY4Njg4Mn0.gCr2QrAJ5wZjcNXSxsJIrfdATd_BPHJqAzx2KhHUrvs

### Add a new building
POST http://localhost:3000/api/buildings/AddBuilding
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}


{
    "propertyName": "Sunset Apartments",
    "locationName": "Nairobi",
    "x": "1",
    "y": "2",
    "type": "STANDALONE",
    "propertyOwner": "b5e86f6c-54b3-4c9b-8cf9-386d1411fb4c"
}


### Fetch All Buildings
GET http://localhost:3000/api/buildings/FetchBuildings
Authorization: {{AUTH_TOKEN}}
